[package]
name = "day14"
version = "0.1.0"
edition = "2021"

[dependencies]
parse-display = "0.7.0"
range-map = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
